### ISSUE TITLE
Can no longer zoom into embedded form

### ISSUE THREAD

**Issue by benmgreene** [hellosign/hellosign-embedded#141]
Hi there,

We've noticed that we can no longer use standard gestures (or any other method, for that matter) to zoom into our embedded forms. Additionally, when clicking the Next Field button, the page is no longer directed to and zoomed in for that field.

Was this behavior change intended?

Our implementation hasn't changed in a year. Is it possible to test with previous versions of the SDK? I've tried all reasonable modifications to `https://s3.amazonaws.com/cdn.hellosign.com/public/js/hellosign-embedded.LATEST.min.js` but haven't found anything that works.

Thanks
--Ben

**Comment by nathanbuchar** [comment]
This sounds like an issue with our signing app. I'll fw to the team!

**Comment by benmgreene** [comment]
Thanks very much!

**Comment by alexmac05** [comment]
Thank you for reporting this issue, Ben.

We are in fact aware of this case and actively working on refactoring the signing module for mobile devices.

I've filed a ticket on your behalf in case you have any further question # 10232754. We will let you know when the fix is released. It is being actively developed so while I cannot give an exact time or date, I can tell you the fix is being developed. 

Please let me know if you have any additional questions, I'd be happy to help! Just respond to the email you have received for the issue. Or email apisupport@hellosign.com for further questions.

**Comment by benmgreene** [comment]
Hi Alex,

I feel like I’m not in on the joke here… this used to work, and you guys broke it. Is there at least a previous version of the library we can use? Dropbox Support gave me a *very* poor reply that clearly doesn’t even realize I am current customer (see below). In any case, if you guys can’t get it together, looks like you’ve got some competitors who have.

Email from support:

> Hi Ben,
> 
> Thanks for writing in today, and for your interest in our API.
> 
> After checking with the engineering team, we were informed that they are actively working on refactoring this case for the mobile devices. That said, while we cannot confirm a specific date, we can share that updates are generally looked at within a few months.
> 
> To better assist you, we wanted to ask you some additional questions.
> 
> Are you planning on using non-embedded or embedded signing with your workflow?
> Approximately how many signatures per month do you think you will be needing? 50, 150, or 450+?
> Could you give us a more detailed idea of your use case?
> If you would like a sales person to call you back, please use this link to contact them: Contact HelloSign Sales Department
> Are you associated with a business contact or a paid HelloSign.com <http://hellosign.com/> Account that we should note in our records? Are you the developer of the project or the business contact or both?

**Comment by alexmac05** [comment]
Hi Ben, 

Dropbox support is us. It might help if we got on a call? Maybe if you could talk to us face to face? Basically, we know it is broken and we are planning to fix it in the short term.

**Comment by alexmac05** [comment]
@hazemhamedhs is going to reachout to you to offer you a link to schedule a call so we can talk this over. I'm sorry that our response was confusing. We were trying to send you the update information that we acknowledge the issue and that we are planning to fix it. We don't give out dates for fixes because it becomes too hard to manage changing dates with releases, but it is acknowledged as an issue that we are planning to fix.

**Comment by alexmac05** [comment]
Also, this issue is not with our embedded.js library but rather with our signer page, which is represented in another code base than the one represented on this github repo. So, we should be talking in the dropbox support ticket vs. this git hub repo. Hope this makes sense and also I think a call will go a long way to building up our relationship. We do want to smooth this over. It is the same exact team (dropbox support and those of us answering this github repo)

**Comment by benmgreene** [comment]
Hi Alex — thanks for the clarification. Yes I’m aware of the Dropbox acquisition. What really rubbed me quite the wrong way is that they didn’t bother to look up our account, they just asked me prospecting questions.

In any case, I’d love to know if there’s a way I can use an older version of the library until the fix is complete — this is a really big deal for us, as I imagine it is for many of your mobile embedded customers — asking someone to sign something they can’t possibly read is hysterically bad.

Also, from looking at the code, it looks pretty clear that the zooming was disabled on purpose (perhaps because it wasn’t working properly), as the user-scalable property is explicitly set to false in the loading script.

Best
—Ben

**Comment by alexmac05** [comment]
I'm not sure if there is but Hazem will know. I'll let him know this is where you are leaning. Thank you for your patience.
