### ISSUE TITLE
difficulties integrating hellosign-embedded with react-native

### ISSUE THREAD

**Issue by Muddahany** [hellosign/hellosign-embedded#156]
Currently I am working my way in testing adding the embedded signing feature into our tablet app. I was able successfully to create a signUrl from our server side. Below is the error thrown whenever I import 'hellosign-embedded'.
```
ReferenceError: Can't find variable: document

memoize$argument_0
    embedded.development.js:6234:8
<anonymous>
    embedded.development.js:6223:42
module.exports
    embedded.development.js:6291:94
srcSassEmbeddedScss
    embedded.development.js:9161:13
__webpack_require__
    embedded.development.js:30:11
_
    embedded.development.js:9372:19
__webpack_require__
    embedded.development.js:30:11
<anonymous>
    embedded.development.js:94:36
<anonymous>
    embedded.development.js:11:16
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:104466:91
<global>
    embedded.development.js:1
loadModuleImplementation
    require.js:321:11
<global>
    index.js:1:24
loadModuleImplementation
    require.js:321:11
<global>
    App.js:3
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:111677:3

```

**Comment by hazemhamedhs** [comment]
Hi Mohamed,

Thank you for reaching out, and sorry for the inconvenience caused. 

Going off the error message you are running into, it sounds like this may be caused by the way in which the signer page is being opened in the iframe. 

Can you please check your email for a ticket that we created with you #10901346 detailing a possible workaround. In general, here are a couple of notes that you can take advantage of when using the API when developing mobile native apps or responsive pages:
https://faq.hellosign.com/hc/en-us/articles/115001896207-Using-the-API-when-developing-mobile-native-apps-or-responsive-pages

Feel free to get back to us via ticket #10901346 or by emailing us at apisupport@hellosign.com

**Comment by RameshDev92** [comment]
Hi @Muddahany and @hazemhamedhs 

I am also getting the same error when i am trying to integrate this in my react native mobile application.

Can you please share me your code if you have resolved this.

Thank you.
