### ISSUE TITLE
Event name change in v2 can cause target origin error 

### ISSUE THREAD

**Issue by erosiec** [hellosign/hellosign-embedded#163]
The v1 event **HelloSign.EVENT_SENT** was renamed to **send** in v2 and this can result in a target origin error when completing some embedded workflows. 

Error message: 
 ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://app.hellosign.com’) does not match the recipient window’s origin (‘https://usersdomain.here’)

Is it possible to update the migration guide or the 'Events' section of the documentation to reflect the v1 counterparts of any event names that were changed in v2?

**Comment by nathanbuchar** [comment]
Hey @erosiec, sorry for the delay. I'm trying to think how the event name changes could result in the target origin mismatch error, but I'm at a loss. I have a few q's:

1. Are you still experiencing target origin mismatch issues?
2. If not, did the issue resolve after using Embedded V2's `"send"` (aka `HelloSign.events.SEND`) instead of V1's `HelloSign.EVENT_SEND`?
3. Would you be interested in someone from our API Support team following up with you to help suss out what's happening?

**Comment by nathanbuchar** [comment]
btw the note about listing the v2 event counterparts in the upgrade guide is a good suggestion, I'll add that to my queue

**Comment by nathanbuchar** [comment]
Just followed up with our team and it looks like everything has already been resolved. Please do let me know if you think this issue needs to be reopened! I'
