### ISSUE TITLE
On load

### ISSUE THREAD

**Issue by NikhilPunwaney** [hellosign/hellosign-embedded#75]
While using this, there are many times that the load time is pretty long and people might X out of it because they think something is broken. Is there any way to have a "onLoad" parameter that takes in an object so that we can communicate that it is loading in the meanwhile?

**Comment by nathanbuchar** [comment]
Unfortunately this capability does not exist at the moment, but we are gearing up to release HelloSign Embedded v2 within the next month. This will have the capability to hook into the `initialize` event, which is triggered when the HelloSign Signer app has loaded and the JavaScript has initialized (essentially "ready").

```js
const client = new HelloSign({ clientId );

client.on(HelloSign.events.INITIALIZE, () => {
  hideLoading();
});

client.open(signUrl);

showLoading();
```

I actually like the idea of calling this event `ready` instead of `initialize`, and it may end up changing in the final release.

**Comment by kodermax** [comment]
New events did not help.
When the ready event fires, your loading continues to be displayed

**Comment by hazemhamedhs** [comment]
Hi @kodermax,
Thank you for reaching out, and sorry for the inconvenience caused. 
Would mind filing a ticket to apisupport@hellosign.com with your code snippet and exact steps to reproduce so we can dig deeper on our end and assist you further.
The more detail you can provide, the easier this should be to figure out.
