### ISSUE TITLE
adding signatures on small screen

### ISSUE THREAD

**Issue by badpk** [hellosign/hellosign-embedded#82]
hello, I am unable to use the buttons on a small screen/mobile device. here is a screenshot:

<img width="227" alt="screen shot 2018-10-10 at 4 08 33 pm" src="https://user-images.githubusercontent.com/3174282/46763107-f319ec80-cca6-11e8-811c-f148d9451b2a.png">

**Comment by nathanbuchar** [comment]
Hi @badpk,

Which device are you using?

Oh, actually, this looks like it's the signature request _editor_ which unfortunately isn't officially supported on mobile as of yet.

**Comment by badpk** [comment]
@nathanbuchar this is the desktop chrome iphone view and it looks the same on a real iphone. 

will the signature request editor be responsive in v2? thanks.

**Comment by nathanbuchar** [comment]
HelloSign Embedded is actually just the wrapper around the app itself and has no bearing on the UI. The buttons, canvas, and everything else you're seeing is living in an iFrame and hosted on app.hellosign.com.

At present, editor support for mobile isn't a _high_ priority, since – as far as we're aware – it's not a common use case. However, I'll be sure to bring it up :)
