### ISSUE TITLE
Remove border box

### ISSUE THREAD

**Issue by kodermax** [hellosign/hellosign-embedded#92]
How can i remove border box?
![image](https://user-images.githubusercontent.com/590985/49218214-e41b0500-f3e0-11e8-94c1-8e6eb051a366.png)

**Comment by Framinus** [comment]
Hi Max,

The blue border is a focus field that highlights the current field in your signer flow. The border is surrounding the entire group of checkboxes because you are using the group checkboxes feature, which shows the user that one of the boxes in that particular group is required to be checked. Once you are no longer focused on that panel of checkboxes, the blue border will move to highlight focus on the next field on the document. The placement of the checkboxes on different pages of the form is what is causing the line to extend so far down the page. 

If you have any further questions, please email us at apisupport@hellosign.com, and we can help you there!
